### ISSUE TITLE
MemoryError with bn.fit_cpds()

### ISSUE THREAD

**Issue by huanyi89** [quantumblacklabs/causalnex#116]
When working with Fit Conditional Probability Distributions, the bn.fit_cpds produces MemoryError: Unable to allocate 346. MiB for an array with shape (3, 30233088) and data type int32.

The training data size is (524,51), the learned structure model size is 20 after removing weak connections. The continuous columns are discretized into 3 bins with fixed method.  This data size is very similar to the example data provided in the CausalNex tutorial. I can run the tutorial successfully but get the following MemoryError with my own dataset.

I am not sure what is the problem, or how to fix it. Thank you 
---------------------------------------------------------------
Here is the error message:

bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")
Traceback (most recent call last):

  File "<ipython-input-90-f1146fdda266>", line 1, in <module>
    bn = bn.fit_cpds(train, method="BayesianEstimator", bayes_prior="K2")

  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\causal_test\lib\site-packages\causalnex\network\network.py", line 371, in fit_cpds
    state_names=state_names,

  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\causal_test\lib\site-packages\pgmpy\models\BayesianModel.py", line 521, in fit
    cpds_list = _estimator.get_parameters(**kwargs)

  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\causal_test\lib\site-packages\pgmpy\estimators\BayesianEstimator.py", line 88, in get_parameters
    pseudo_counts=_pseudo_counts,

  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\causal_test\lib\site-packages\pgmpy\estimators\BayesianEstimator.py", line 161, in estimate_cpd
    pseudo_counts = np.ones(cpd_shape, dtype=int)

  File "C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\numpy\core\numeric.py", line 192, in ones
    a = empty(shape, dtype, order)

MemoryError: Unable to allocate 346. MiB for an array with shape (3, 30233088) and data type int32

Environment:
Windows system, python 3.6, CausalNex 0.9.2

**Comment by oentaryorj** [comment]
Hi @huanyi89, thanks for raising the issue. Is there a way you could provide the data and script you used, so that we can replicate this?

**Comment by oentaryorj** [comment]
Closing this for now, as there is insufficient information about the data to reproduce the error.  Feel free to reopen the issue if the problem persists.
